apiVersion: v1
kind: Template
message: |-
  The following service(s) have been created in your project: ${NAME}.

  For more information about using this template, including OpenShift considerations, see https://github.com/jameseck/openshift-templates
metadata:
  annotations:
    description: This template assumes you will have torrents and tv volumes already defined.
    iconClass: fa fa-television
    openshift.io/display-name: Squid+VPN
    openshift.io/documentation-url: https://github.com/jameseck/openshift-templates
    openshift.io/long-description: This template defines resources needed to run Squid with OpenVPN.
    openshift.io/provider-display-name: James Eckersall
    openshift.io/support-url: https://github.com/jameseck/openshift-templates
    tags: proxy
    template.openshift.io/bindable: 'false'
  name: proxyvpn
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: proxyvpn
    labels:
      app: ${NAME}
  spec:
    dockerImageRepository: act28/pia-openvpn-proxy
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: act28/pia-openvpn-proxy
        importPolicy:
          scheduled: true
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 4
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - command: ["/bin/sh"]
          args:
          - -c
          - mkdir /dev/net && mknod /dev/net/tun c 10 200 && runsvdir /app
          env:
          - name: USERNAME
            value: "${USERNAME}"
          - name: PASSWORD
            value: "${PASSWORD}"
          - name: REGION
            value: "${REGION}"
          - name: LOCAL_NETWORK
            value: "${LOCAL_NETWORK}"
          image: " "
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 5
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 5
          name: proxyvpn
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        serviceAccount: ${NAME}
        serviceAccountName: ${NAME}
        terminationGracePeriodSeconds: 30
    securityContext:
      privileged: true
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - proxyvpn
        from:
          kind: ImageStreamTag
          name: proxyvpn:latest
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    host: ${SITE_URL}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${NAME}
      weight: 100
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: ${NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  name: NAME
  displayName: Name
  value: proxyvpn
  required: true
- description: The URL for this application
  name: SITE_URL
  displayName: Site URL
  value: ""
- description: PIA Username
  name: USERNAME
  displayName: Username
  value: ""
- description: PIA Password
  name: PASSWORD
  displayName: Password
  value: ""
- description: PIA Region
  name: REGION
  displayName: PIA Region
  value: "UK London"
- description: Local Network
  name: LOCAL_NETWORK
  displayName: Local Network
  value: "172.30.0.0/16"
