apiVersion: v1
kind: Template
message: |-
  The following service(s) have been created in your project: ${NAME}.

  For more information about using this template, including OpenShift considerations, see https://github.com/jameseck/openshift-templates
metadata:
  annotations:
    description: This template assumes you will have torrents, downloads and tv volumes already defined.
    iconClass: fa fa-music
    openshift.io/display-name: Airsonic
    openshift.io/documentation-url: https://github.com/jameseck/openshift-templates
    openshift.io/long-description: This template defines resources needed to run
      Airsonic.
    openshift.io/provider-display-name: James Eckersall
    openshift.io/support-url: https://github.com/jameseck/openshift-templates
    tags: airsonic
    template.openshift.io/bindable: 'false'
  name: airsonic
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    creationTimestamp: null
    generation: 2
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: airsonic/airsonic
      from:
        kind: DockerImage
        name: airsonic/airsonic:latest
      generation: 5
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - env:
          - name: AIRSONIC_PORT
            value: "4040"
          - name: JAVA_OPTS
            value: "${JAVA_OPTS}"
          image: " "
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /login
              port: 4040
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: airsonic
          ports:
          - containerPort: 4040
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /login
              port: 4040
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /airsonic/music
            name: airsonic-music
          - mountPath: /airsonic/data
            name: airsonic-data
          - mountPath: /airsonic/playlists
            name: airsonic-playlists
          - mountPath: /airsonic/podcasts
            name: airsonic-podcasts
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: airsonic-music
          persistentVolumeClaim:
            claimName: ${MUSIC_PVC}
        - name: airsonic-data
          persistentVolumeClaim:
            claimName: airsonic-data
        - emptyDir: {}
          name: airsonic-playlists
        - emptyDir: {}
          name: airsonic-podcasts
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - airsonic
        from:
          kind: ImageStreamTag
          name: airsonic:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      kubernetes.io/tls-acme: "true"
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    host: ${SITE_URL}
    port:
      targetPort: 4040-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - name: 4040-tcp
      port: 4040
      protocol: TCP
      targetPort: 4040
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  name: NAME
  displayName: Name
  value: airsonic
  required: true
- description: The URL for this application
  name: SITE_URL
  displayName: Site URL
  value: ""
- description: The name of existing PVC where Music is stored
  name: MUSIC_PVC
  displayName: Music PVC
  value: music
  required: true
- description: The size of the config volume
  name: CONFIG_VOLUME_SIZE
  displayName: Config Volume Size
  value: 1Gi
  required: true
- description: Options to pass to Java
  name: JAVA_OPTS
  displayName: JAVA_OPTS
  value: -Dserver.use-forward-headers=true
  required: true
